apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapyrt
  namespace: gitlab-managed-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scrapyrt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scrapyrt
    spec:
      containers:
      - name: scrapyrt
        image: greenw00d/oasis-scrapy:TAG
        imagePullPolicy: Always
        env:
          - name: MONGOHOST
            value: mongodb://se3-shard-mongos-0.se3-shard-svc.mongodb.svc.cluster.local,se3-shard-mongos-1.se3-shard-svc.mongodb.svc.cluster.local
          - name: COLLNAME
            value: large
        readinessProbe:
            periodSeconds: 10
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
        livenessProbe:
            periodSeconds: 10
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
        resources:
          requests:
            memory: "300M"
            cpu: "0.25"
          limits:
            memory: "400M"
            cpu: "0.5"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: scrapyrt-svc
  namespace: gitlab-managed-apps
spec:
  ports:
  - port: 80
    targetPort: 80
    name: scrapyrt-svc
  selector:
    app: scrapyrt
  type: NodePort