name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push Docker image
      with:
        image: greenw00d/backend-scrapy
        tag: latest
        dockerfile: Dockerfile
        registry: docker.io
        username: greenw00d
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: deploy in remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker pull greenw00d/backend-scrapy
          docker stop backend-scrapy
          docker rm backend-scrapy
          docker run --name=backend-scrapy --restart=always --network="host" -p 80:80 -d greenw00d/backend-scrapy
