name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push backend image
      with:
        image: greenw00d/backend-scrapy
        tag: latest
        dockerfile: backend.dockerfile
        registry: docker.io
        username: greenw00d
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push celery image
      with:
        image: greenw00d/celeryworker
        tag: latest
        dockerfile: celeryworker.dockerfile
        registry: docker.io
        username: greenw00d
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: deploy in remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker pull greenw00d/celeryworker
          docker stop celeryworker
          docker rm celeryworker
          docker run --env MONGOHOST=${{ secrets.MONGOHOST }} --name=celeryworker --restart=always --network="host" -d greenw00d/celeryworker
          docker pull greenw00d/backend-scrapy
          docker stop backend-scrapy
          docker rm backend-scrapy
          docker run --env MONGOHOST=${{ secrets.MONGOHOST }} --name=backend-scrapy --restart=always --network="host" -p 80:80 -d greenw00d/backend-scrapy
